### ISSUE TITLE
Incorrectly generated "default" line in swagger.json

### ISSUE THREAD

**Issue by Garagoth** [stoicflame/enunciate#119]
Enunciate 2.0.0-M.3 docs failing with:

```
[DEBUG] [ENUNCIATE] Processing template jar:file:/home/garagoth/.m2/repository/com/webcohesion/enunciate/enunciate-swagger/2.0.0-M.3/enunciate-swagger-2.0.0-M.3.jar!/com/webcohesion/enunciate/modules/swagger/swagger.fmt.
[WARNING] [ENUNCIATE] Error processing /home/garagoth/PRES/pres-dev/API/target/site/apidocs/ui/swagger.json.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 39.412 s
[INFO] Finished at: 2015-08-29T22:03:05+02:00
[INFO] Final Memory: 106M/379M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-M.3:docs (default-cli) on project API: Execution default-cli of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-M.3:docs failed: com.webcohesion.enunciate.EnunciateException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('"' (code 34)): was expecting comma to separate OBJECT entries
[ERROR] at [Source: java.io.FileReader@11364e5a; line: 13646, column: 14]: OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-M.3:docs (default-cli) on project API: Execution default-cli of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-M.3:docs failed: com.webcohesion.enunciate.EnunciateException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('"' (code 34)): was expecting comma to separate OBJECT entries
 at [Source: java.io.FileReader@11364e5a; line: 13646, column: 14]
```

looking at the swagger.json file it shows errors in structure (please see "default" key, there is no , char at the end of line making json incorrect):
```
"/crm/service-items/log-history" : {
      "get" : {
        "tags" : [ "CRM" ],
        "description" : "",
        "operationId" : "resource_CRM_serviceItemLogHistory_GET",
        "produces" : [ "application/json" ],
        "parameters" : [
          {
            "name" : "logId",
            "in" : "query",
            "type" : "string",
            "description" : ""
          },
          {
            "name" : "page",
            "in" : "query",
            "default" : "1"
            "type" : "string",
            "description" : ""
          },

```

Those are method parameter annotations:
```
@QueryParam("page") @DefaultValue("1") short page
```
(also, marked as type: string in json while it is short, is that correct?)

Regards,
Garagoth.

**Comment by Garagoth** [comment]
And not sure about this, complains about defaultValue as well, so putting here as well:
```
Aug 29, 2015 10:25:14 PM freemarker.log._JULLoggerFactory$JULLogger error
SEVERE: Error executing FreeMarker template
FreeMarker template error:
An error has occurred when reading existing sub-variable "defaultValue"; see cause exception! The type of the containing value was: extended_hash+string (com.webcohesion.enunciate.modules.jackson.model.Member wrapped into f.e.b.StringModel)

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #if member.defaultValue??  [in template "jar:file:/home/garagoth/.m2/repository/com/webcohesion/enunciate/enunciate-java-json-client/2.0.0-M.3/enunciate-java-json-client-2.0.0-M.3.jar!/com/webcohesion/enunciate/modules/java_json_client/client-complex-type.fmt" at line 100, column 75]
	- Reached through: @file name=((type.simpleName + ".java...  [in template "jar:file:/home/garagoth/.m2/repository/com/webcohesion/enunciate/enunciate-java-json-client/2.0.0-M.3/enunciate-java-json-client-2.0.0-M.3.jar!/com/webcohesion/enunciate/modules/java_json_client/client-complex-type.fmt" at line 5, column 1]
----

Java stack trace (for programmers):
----
freemarker.core._TemplateModelException: [... Exception message was already printed; see it above ...]
	at freemarker.ext.beans.BeanModel.get(BeanModel.java:199)
	at freemarker.core.Dot._eval(Dot.java:40)
	at freemarker.core.Expression.eval(Expression.java:78)
	at freemarker.core.ExistsExpression._eval(ExistsExpression.java:45)
	at freemarker.core.Expression.eval(Expression.java:78)
	at freemarker.core.Expression.evalToBoolean(Expression.java:118)
	at freemarker.core.Expression.evalToBoolean(Expression.java:110)
	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:46)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.MixedContent.accept(MixedContent.java:62)
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
	at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:159)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:559)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:67)
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
	at freemarker.core.IfBlock.accept(IfBlock.java:48)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.MixedContent.accept(MixedContent.java:62)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.Environment$NestedElementTemplateDirectiveBody.render(Environment.java:2255)
	at com.webcohesion.enunciate.util.freemarker.FileDirective.execute(FileDirective.java:59)
	at freemarker.core.Environment.visit(Environment.java:377)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:104)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.MixedContent.accept(MixedContent.java:62)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.Environment.process(Environment.java:290)
	at freemarker.template.Template.process(Template.java:312)
	at com.webcohesion.enunciate.modules.java_json_client.JavaJSONClientModule.processTemplate(JavaJSONClientModule.java:248)
	at com.webcohesion.enunciate.modules.java_json_client.JavaJSONClientModule.generateClientSources(JavaJSONClientModule.java:164)
	at com.webcohesion.enunciate.modules.java_json_client.JavaJSONClientModule.call(JavaJSONClientModule.java:115)
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:31)
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:10)
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:79)
	at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:109)
	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:140)
	at rx.internal.operators.TakeLastQueueProducer.emit(TakeLastQueueProducer.java:100)
	at rx.internal.operators.TakeLastQueueProducer.startEmitting(TakeLastQueueProducer.java:45)
	at rx.internal.operators.OperatorTakeLast$1.onCompleted(OperatorTakeLast.java:59)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:658)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
	at rx.internal.util.ScalarSynchronousObservable$ScalarSynchronousAction.call(ScalarSynchronousObservable.java:117)
	at rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173)
	at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor167.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1458)
	at freemarker.ext.beans.BeanModel.invokeThroughDescriptor(BeanModel.java:255)
	at freemarker.ext.beans.BeanModel.get(BeanModel.java:159)
	... 54 more
Caused by: java.lang.annotation.IncompleteAnnotationException: com.fasterxml.jackson.annotation.JsonProperty missing element defaultValue
	at sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:80)
	at com.sun.proxy.$Proxy44.defaultValue(Unknown Source)
	at com.webcohesion.enunciate.modules.jackson.model.Member.getDefaultValue(Member.java:274)
	... 60 more

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23.870 s
[INFO] Finished at: 2015-08-29T22:25:14+02:00
[INFO] Final Memory: 118M/382M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project API: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.3:site failed: com.webcohesion.enunciate.EnunciateException: freemarker.core._TemplateModelException: An error has occurred when reading existing sub-variable "defaultValue"; see cause exception! The type of the containing value was: extended_hash+string (com.webcohesion.enunciate.modules.jackson.model.Member wrapped into f.e.b.StringModel)
[ERROR] 
[ERROR] ----
[ERROR] FTL stack trace ("~" means nesting-related):
[ERROR] - Failed at: #if member.defaultValue??  [in template "jar:file:/home/garagoth/.m2/repository/com/webcohesion/enunciate/enunciate-java-json-client/2.0.0-M.3/enunciate-java-json-client-2.0.0-M.3.jar!/com/webcohesion/enunciate/modules/java_json_client/client-complex-type.fmt" at line 100, column 75]
[ERROR] - Reached through: @file name=((type.simpleName + ".java...  [in template "jar:file:/home/garagoth/.m2/repository/com/webcohesion/enunciate/enunciate-java-json-client/2.0.0-M.3/enunciate-java-json-client-2.0.0-M.3.jar!/com/webcohesion/enunciate/modules/java_json_client/client-complex-type.fmt" at line 5, column 1]
[ERROR] ----: InvocationTargetException: com.fasterxml.jackson.annotation.JsonProperty missing element defaultValue: OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

This is from enunciate:docs invoked as part of site report.

**Comment by jellenelis** [comment]
I seem to have a similar problem.

<pre>[ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-M.3:assemble (assemble) on project enunciate-reporting-issue: Execution assemble of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-M.3:assemble failed: com.webcohesion.enunciate.EnunciateException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('"' (code 34)): was expecting comma to separate OBJECT entries
[ERROR] at [Source: java.io.FileReader@4868ee2e; line: 32, column: 14]: OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class
[ERROR] -> [Help 1]</pre>

The swagger.json that is constructed is missing a comma in the parameter section after schema and before description. Having Javadoc for the method (the original situation) does not change anything (other than the description not being the empty string).
<pre>
{
  "swagger": "2.0",
  "info" : {
    "description" : "&lt;h1&gt;Enunciate reporting test&lt;\/h1>&lt;p&gt;Enunciate reporting test&lt;\/p&gt;",
    "version" : "0.1-SNAPSHOT",
    "title" : "Enunciate reporting test"
  },
  "basePath" : "/",
  "tags" : [
    {
      "name" : "ExampleResource",
      "description" : ""
    }
  ],
  "definitions" : {
  },
  "paths": {
    "/example/{sessionID}" : {
      "post" : {
        "tags" : [ "ExampleResource" ],
        "description" : "",
        "operationId" : "resource_ExampleResource_post_POST",
        "consumes" : [  ],
        "produces" : [  ],
        "parameters" : [
          {
            "name" : "body",
            "in" : "body",
            "schema" : {
              "type" : "object"
            }
            "description" : ""
          }
        ],
        "responses" : {
          "201" : {
            "headers" : {
            },
            "description" : "Success"
          },
          "default" : {
            "description" : "Unexpected error."
          }
        }
      }
    }
  }
}
</pre>

I created a self-contained project that shows the problem, you can find it at https://www.dropbox.com/s/5q61f6uuiuevvcw/testEnunciate.tar.gz?dl=0 , the application I am developing uses Dropwizard, removing the dropwizard dependency changes the error into an error saying nothing is found to document.

**Comment by stoicflame** [comment]
Okay, thanks for the report. I'll fix that ASAP.

For now, just disable the swagger module as a workaround.

```xml
<enunciate>
  <modules>
    <swagger disabled="true"/>
```

**Comment by stoicflame** [comment]
Fixed at 6d1c558.

**Comment by jellenelis** [comment]
I believe you are still missing a comma on line 163 of com/webcohesion/enunciate/modules/swagger/swagger.fmt to fix the error I reported

**Comment by stoicflame** [comment]
Ah. Yep. Good catch. Fixed at 627bdab.

**Comment by stoicflame** [comment]
Fix was included in [Milestone 4](https://github.com/stoicflame/enunciate/releases/tag/v2.0.0-M.4). Thanks for the report, and please report any new issues.
