### ISSUE TITLE
M4: enunciate:docs crashes

### ISSUE THREAD

**Issue by anton-johansson** [stoicflame/enunciate#137]
Hi!

Just bumped up to the M4-release, and it didn't quite work out. I got this log:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building <artifactName> 0.0.0.Dev-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- enunciate-maven-plugin:2.0.0-M.4:docs (default-cli) @ <artifactId> ---
[INFO] [ENUNCIATE] Using enunciate configuration at C:\Users\<username>\Projects\<project>\enunciate.xml
[INFO] Reflections took 905 ms to scan 27 urls, producing 342 keys and 342 values 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.924 s
[INFO] Finished at: 2015-09-10T22:10:49+01:00
[INFO] Final Memory: 39M/454M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-M.4:docs (default-cli) on project <artifactId>: Execution default-cli of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-M.4:docs failed: java.lang.annotation.AnnotationTypeMismatchException: Incorrectly typed data found for annotation element public abstract java.lang.String javax.xml.bind.annotation.XmlSchema.namespace() (Found data of type java.lang.String): OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

Also, first time I executed it, it gave me exactly the same as above, and also this beneath:
```
Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: com/webcohesion/enunciate/modules/jaxws/EnunciateJaxwsContext
	at com.webcohesion.enunciate.modules.jaxws.JaxwsModule.call(JaxwsModule.java:88)
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:31)
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:10)
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:79)
	at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:109)
	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:140)
	at rx.internal.operators.TakeLastQueueProducer.emit(TakeLastQueueProducer.java:100)
	at rx.internal.operators.TakeLastQueueProducer.startEmitting(TakeLastQueueProducer.java:45)
	at rx.internal.operators.OperatorTakeLast$1.onCompleted(OperatorTakeLast.java:59)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:658)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
	at rx.internal.util.ScalarSynchronousObservable$ScalarSynchronousAction.call(ScalarSynchronousObservable.java:117)
	at rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173)
	at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ClassNotFoundException: com.webcohesion.enunciate.modules.jaxws.EnunciateJaxwsContext
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
	... 19 more
```

Couldn't reproduce the stacktrace, but I'm assuming it's the same error anyway. It's atleast the same error message when it fails.

I tried to disable the jaxws module:
```<jaxws disabled="true" />```

... but still gives me the same error.

**Comment by stoicflame** [comment]
It's some kind of nasty classloading issue. The error is basically saying "I expected a java.lang.String, but I got a java.lang.String".

Can you give me any tips on how to reproduce it?

**Comment by anton-johansson** [comment]
I'll try to provide more information tomorrow!

**Comment by stoicflame** [comment]
Another instance of `NoClassDefFoundError` reported at #138. That user was using Eclipse; the project seems to build fine from the command line.

But I'm still not able to reproduce the problem...

**Comment by anton-johansson** [comment]
I'm using Eclipse as well. I'll try using the command line too.

**Comment by anton-johansson** [comment]
Using the command line didn't work for me, but it gave me another error:

```
C:\Users\<username>\Projects\<project>>mvn enunciate:docs
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building <artifactName> 0.0.0.Dev-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- enunciate-maven-plugin:2.0.0-M.4:docs (default-cli) @ <artifactId> ---
[INFO] [ENUNCIATE] Using enunciate configuration at C:\Users\<username>\Projects\<project>\enunciate.xml
sep 13, 2015 2:38:27 EM org.reflections.Reflections scan
INFO: Reflections took 928 ms to scan 27 urls, producing 346 keys and 346 values
Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: javax/inject/Named
        at org.jvnet.hk2.external.generator.ServiceLocatorGeneratorImpl.initialize(ServiceLocatorGeneratorImpl.java:71)
        at org.jvnet.hk2.external.generator.ServiceLocatorGeneratorImpl.create(ServiceLocatorGeneratorImpl.java:96)
        at org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.internalCreate(ServiceLocatorFactoryImpl.java:251)
        at org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.create(ServiceLocatorFactoryImpl.java:228)
        at org.glassfish.jersey.internal.inject.Injections._createLocator(Injections.java:142)
        at org.glassfish.jersey.internal.inject.Injections.createLocator(Injections.java:113)
        at org.glassfish.jersey.server.internal.RuntimeDelegateImpl.<init>(RuntimeDelegateImpl.java:63)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at java.lang.Class.newInstance(Class.java:374)
        at javax.ws.rs.ext.FactoryFinder.newInstance(FactoryFinder.java:65)
        at javax.ws.rs.ext.FactoryFinder.find(FactoryFinder.java:117)
        at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:105)
        at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:91)
        at javax.ws.rs.core.MediaType.<clinit>(MediaType.java:44)
        at com.webcohesion.enunciate.modules.jaxrs.EnunciateJaxrsContext.addJAXRSProvider(EnunciateJaxrsContext.java:225)
        at com.webcohesion.enunciate.modules.jaxrs.JaxrsModule.call(JaxrsModule.java:69)
        at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:31)
        at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:10)
        at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:79)
        at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:109)
        at rx.internal.operators.NotificationLite.accept(NotificationLite.java:140)
        at rx.internal.operators.TakeLastQueueProducer.emit(TakeLastQueueProducer.java:100)
        at rx.internal.operators.TakeLastQueueProducer.startEmitting(TakeLastQueueProducer.java:45)
        at rx.internal.operators.OperatorTakeLast$1.onCompleted(OperatorTakeLast.java:59)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:658)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
        at rx.internal.util.ScalarSynchronousObservable$ScalarSynchronousAction.call(ScalarSynchronousObservable.java:117)
        at rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173)
        at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ClassNotFoundException: javax.inject.Named
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:244)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:230)
        ... 41 more
```

As far as I can tell, we don't use the Named annotation anywhere in our project. If I open up "Open Type" in Eclipse and enter "javax.inject.Named", I get two occurrences in two different .jar files. However, there's a lot of projects/bundles open. Neither of these two jars are in the dependency hierarchy of the project I'm running "enunciate:docs" on.

Other than that, we're using the regular annotations:
 * ```javax.ws.rs.Path```
 * ```javax.ws.rs.GET```
 * ```javax.ws.rs.PathParam```
 * ```javax.xml.bind.annotation.XmlRootElement```
 * ```javax.xml.bind.annotation.XmlAccessorType```

We're using CXF version 2.7.5, however I doubt that matters, since Enunciate wouldn't look at that.

Our domain objects (data types) reside in a separate project/bundle, that the REST-project/bundle simply reference.

Is there any specific details you are looking for in order to reproduce the problem? I can try to reproduce my problem in a smaller, scaled down project and send it to you, but that's gonna take some time.

**Comment by stoicflame** [comment]
Okay, I believe that particular `NoClassDefFoundError` is different from the one you get from running it from Eclipse.

Try running "mvn -X enunciate:docs" and look for the enunciate debug messages that say things like "Added <classname> as a JAX-RS root resource". Did Enunciate detect any classes that aren't actually part of your API? If so, which ones?

**Comment by adamrawlings** [comment]
I'm seeing a similar issue with my build (like in #138), except I'm not getting the "NoClassDefFoundError" exception.

```
[DEBUG] [ENUNCIATE] /Users/<user>/Workspace/<project>/api/target/enunciate/java-json-client/classes is NOT up-to-date because it's an empty directory.
warning: [options] bootstrap class path not set in conjunction with -source 1.5
warning: [options] source value 1.5 is obsolete and will be removed in a future release
warning: [options] target value 1.5 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
/Users/<user>/Workspace/<project>/api/target/enunciate/java-json-client/src/javax/ws/rs/core/Response.java:26: error: cannot find symbol
  private javax.ws.rs.core.StatusType _statusInfo;
                          ^
  symbol:   class StatusType
  location: package javax.ws.rs.core
/Users/<user>/Workspace/<project>/api/target/enunciate/java-json-client/src/javax/ws/rs/core/Response.java:118: error: cannot find symbol
  public javax.ws.rs.core.StatusType getStatusInfo() {
                         ^
  symbol:   class StatusType
  location: package javax.ws.rs.core
/Users/<user>/Workspace/<project>/api/target/enunciate/java-json-client/src/javax/ws/rs/core/Response.java:126: error: cannot find symbol
  public void setStatusInfo(javax.ws.rs.core.StatusType _statusInfo) {
                                            ^
  symbol:   class StatusType
  location: package javax.ws.rs.core
3 errors
4 warnings
```

Here's the stack trace after running "mvn -X enunciate:docs" from the command line
```
[ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-M.4:docs (default-cli) on <project>: Execution default-cli of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-M.4:docs failed: com.webcohesion.enunciate.EnunciateException: Compile failed of Java client-side classes. OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-M.4:docs (default-cli) on <project>: Execution default-cli of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-M.4:docs failed: com.webcohesion.enunciate.EnunciateException: Compile failed of Java client-side classes.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0-M.4:docs failed: com.webcohesion.enunciate.EnunciateException: Compile failed of Java client-side classes.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:144)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.RuntimeException: com.webcohesion.enunciate.EnunciateException: Compile failed of Java client-side classes.
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at com.webcohesion.enunciate.Enunciate.run(Enunciate.java:650)
	at com.webcohesion.enunciate.mojo.ConfigMojo.execute(ConfigMojo.java:352)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	... 20 more
Caused by: com.webcohesion.enunciate.EnunciateException: Compile failed of Java client-side classes.
	at com.webcohesion.enunciate.modules.java_json_client.JavaJSONClientModule.compileClientSources(JavaJSONClientModule.java:312)
	at com.webcohesion.enunciate.modules.java_json_client.JavaJSONClientModule.call(JavaJSONClientModule.java:116)
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:31)
	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:10)
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:79)
	at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:109)
	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:140)
	at rx.internal.operators.TakeLastQueueProducer.emit(TakeLastQueueProducer.java:100)
	at rx.internal.operators.TakeLastQueueProducer.startEmitting(TakeLastQueueProducer.java:45)
	at rx.internal.operators.OperatorTakeLast$1.onCompleted(OperatorTakeLast.java:59)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:658)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
	at rx.internal.util.ScalarSynchronousObservable$ScalarSynchronousAction.call(ScalarSynchronousObservable.java:117)
	at rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173)
	at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:101)
	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:81)
	... 31 more
```

**Comment by stoicflame** [comment]
Thanks, @adamrawlings. There might be a few different issues occurring. It's really tricky to work it out, especially because I haven't figured out how to reproduce it myself.

I need the output from "mvn -X" where it talks about "Added \<classname\> as a JAX-RS root resource." It should be a hundred or so lines before the stack trace. Are there any classes listed there that surprise you? (e.g. any classes that aren't actually part of the API?)

And again, if there's any way someone could put together a sample project or otherwise describe to me how to reproduce these errors, that would be most helpful.

**Comment by stoicflame** [comment]
At a94e144 and 1b01e1b, the default datatype detection strategy changed so some of these auto-detected resources won't be included into the Enunciate process unless explicitly included in the config. This might help avoid the issue, but it doesn't resolve it. I'm still waiting on some help in reproducing the issue, so this issue will remain open.

**Comment by anton-johansson** [comment]
I haven't had the time to check any further or reproduce it in a smaller
project. Will try to do so once I have time.

**Comment by stoicflame** [comment]
Okay, thanks to @anton-johansson, I've been able to identify three separate issues on this thread.

1. The `NoClassDefFoundError` about `javax/inject/Named`. This was fixed at 7b88ae0.
2. The client-side compile failure about `StatusType`. This was fixed at 7a55b2c.
2. The `NoClassDefFoundError` about Enunciate classes (like `EnunciateJaxwsContext`). This apparently only shows up when building from Eclipse, and has also been reported at #138. I have no way to explain this or debug this until someone can provide me a way to reproduce it.

So I'm going to close out this issue and re-open #138 to track the Eclipse bug. If you're not using Eclipse, the other bugs that were reported here should be fixed.

**Comment by shannhastings** [comment]
Im using 2.3 and I still get the The client-side compile failure about StatusType. Issue,   Using jackson 2.7

**Comment by stoicflame** [comment]
@shannhastings thanks for the report. Can you grep through the output of "mvn -X" and find any references to `StatusType`?

**Comment by shannhastings** [comment]
I was able to get around the problem by not having my compiled API jars included in the build and only including the “source” jars.
