### ISSUE TITLE
swagger.json JsonParseException

### ISSUE THREAD

**Issue by rcpoison** [stoicflame/enunciate#155]
Hi ^^
Getting the following when building the swagger module (using RC.1):

```
Caused by: com.webcohesion.enunciate.EnunciateException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('"' (code 34)): was expecting comma to separate OBJECT entries
 at [Source: java.io.FileReader@2a4dd767; line: 1052, column: 2]
        at com.webcohesion.enunciate.modules.docs.DocsModule.call(DocsModule.java:311)
        at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:31)
        at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:10)
        at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:79)
        at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:109)
        at rx.internal.operators.NotificationLite.accept(NotificationLite.java:140)
        at rx.internal.operators.TakeLastQueueProducer.emit(TakeLastQueueProducer.java:100)
        at rx.internal.operators.TakeLastQueueProducer.startEmitting(TakeLastQueueProducer.java:45)
        at rx.internal.operators.OperatorTakeLast$1.onCompleted(OperatorTakeLast.java:59)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:658)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
        at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onCompleted(SubjectSubscriptionManager.java:232)
        at rx.subjects.ReplaySubject.onCompleted(ReplaySubject.java:404)
        at rx.Observable$35.onCompleted(Observable.java:7458)
        at rx.observers.SafeSubscriber.onCompleted(SafeSubscriber.java:81)
        at rx.internal.operators.OperatorDoOnEach$1.onCompleted(OperatorDoOnEach.java:53)
        at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:110)
        at rx.internal.operators.NotificationLite.accept(NotificationLite.java:140)
        at rx.internal.operators.TakeLastQueueProducer.emit(TakeLastQueueProducer.java:100)
        at rx.internal.operators.TakeLastQueueProducer.startEmitting(TakeLastQueueProducer.java:45)
        at rx.internal.operators.OperatorTakeLast$1.onCompleted(OperatorTakeLast.java:59)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:658)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
        at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
        at rx.internal.util.ScalarSynchronousObservable$ScalarSynchronousAction.call(ScalarSynchronousObservable.java:117)
        at rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173)
        at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

and the json block in question:
```json 
    "json_constructor" : {
      "type" : "object",
      "title" : "Constructor",
      "allOf" : [
        {
          "$ref" : "#/definitions/json_accessibleobject"
        },
        {
          "properties" : {
            "declaringClass" : {
"description" : "",
"$ref" : "#/definitions/json_class"
            },
            "exceptionTypes" : {
"description" : "",
"type" : "array",
"items" : {
  "$ref" : "#/definitions/json_class"
}
            },
            "genericExceptionTypes" : {
"description" : "",
"type" : "array",
"items" : {
  "type" : "object"
}
            },
            "genericParameterTypes" : {
"description" : "",
"type" : "array",
"items" : {
  "type" : "object"
}
            },
            "modifiers" : {
"description" : "",
"type" : "number"
            },
            "name" : {
"description" : "",
"type" : "string"
            },
            "parameterAnnotations" : {
"description" : "",
"type" : "array",
"items" : {
}
"type" : "array",
"items" : {
}
"type" : "array",
"items" : {
  "type" : "object"
}
            },
            "parameterTypes" : {
"description" : "",
"type" : "array",
"items" : {
  "$ref" : "#/definitions/json_class"
}
            },
            "synthetic" : {
"description" : "",
"type" : "boolean"
            },
            "typeParameters" : {
"description" : "",
"type" : "array",
"items" : {
  "type" : "object"
}
            },
            "varArgs" : {
"description" : "",
"type" : "boolean"
            }
          }
        }
      ],
      "description" : ""
    }
```

Notice the missing comma after '"items" : {}'.
Do you need more context?

**Comment by stoicflame** [comment]
Fixed at 1fef684, thanks for the report.

For the record, that datatype implies that somewhere you've got a data type that returns `java.lang.reflect.Constructor` in your API, which probably isn't correct. You may need to apply @JsonIgnore somewhere or exclude some classes from Enunciate doc, or it may be an Enunciate bug. If it's an Enunciate bug, don't hesitate to open another report.

**Comment by rcpoison** [comment]
Thank you very much for the swift fix :)
I'm still struggling to get enunciate to build so I can test immediately,
but I'm definately not exposing an java.lang.reflect.* type anywhere in my API.

**Comment by stoicflame** [comment]
Yeah, the build is a bit tricky because of all the needed client-side code frameworks.

After I work through your other two issues, I'll see if I can manage to figure out how to publish a snapshot version to the [sonatype ossrh](http://central.sonatype.org/pages/ossrh-guide.html) so you can try it out.

**Comment by rcpoison** [comment]
d'oh. I'm sorry, scratch that "definately".
I forgot about this gem:
```java
    @XmlAttribute
	@XmlJavaTypeAdapter(SelectionPluginAdapter.class)
	public Class<? extends SelectionPlugin> getPlugin()
```

But ```SelectionPluginAdapter``` is an ```XmlAdapter<String, Class<? extends SelectionPlugin>>``` and the user only ever interacts with the String so I don't think enunciate should expose Class<?> in the documentation or even scan it.
Should I create a new bug or wait till I can test the next release?

**Comment by stoicflame** [comment]
I've deployed 2.0.0-SNAPSHOT; you're welcome to try it out if you want to use the [OSSRH snapshot repository](https://oss.sonatype.org/content/repositories/snapshots/).

I looked into the issue with adding `java.lang.Class` to the data types at #161. Take a look over there to see the solution.

**Comment by rcpoison** [comment]
Working now, thank you :)

**Comment by rcpoison** [comment]
Swagger still doesn't like the json though, it's a 600kb file I'll try to narrow it down.
